//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.33440.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Iso8583PostXml {
    
    private string msgTypeField;
    
    private Fields fieldsField;
    
    /// <remarks/>
    public string MsgType {
        get {
            return this.msgTypeField;
        }
        set {
            this.msgTypeField = value;
        }
    }
    
    /// <remarks/>
    public Fields Fields {
        get {
            return this.fieldsField;
        }
        set {
            this.fieldsField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.33440")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Fields {
    
    private string field_002Field;
    
    private string field_003Field;
    
    private string field_004Field;
    
    private string field_005Field;
    
    private string field_007Field;
    
    private string field_009Field;
    
    private string field_011Field;
    
    private string field_012Field;
    
    private string field_013Field;
    
    private string field_014Field;
    
    private string field_015Field;
    
    private string field_016Field;
    
    private string field_018Field;
    
    private string field_022Field;
    
    private string field_023Field;
    
    private string field_025Field;
    
    private string field_026Field;
    
    private string field_027Field;
    
    private string field_028Field;
    
    private string field_029Field;
    
    private string field_030Field;
    
    private string field_031Field;
    
    private string field_032Field;
    
    private string field_033Field;
    
    private string field_035Field;
    
    private string field_037Field;
    
    private string field_038Field;
    
    private string field_039Field;
    
    private string field_040Field;
    
    private string field_041Field;
    
    private string field_042Field;
    
    private string field_043Field;
    
    private string field_044Field;
    
    private string field_045Field;
    
    private string field_048Field;
    
    private string field_049Field;
    
    private string field_050Field;
    
    private string field_052Field;
    
    private string field_053Field;
    
    private string field_054Field;
    
    private string field_056Field;
    
    private string field_057Field;
    
    private string field_058Field;
    
    private string field_059Field;
    
    private string field_066Field;
    
    private string field_067Field;
    
    private string field_070Field;
    
    private string field_073Field;
    
    private string field_074Field;
    
    private string field_075Field;
    
    private string field_076Field;
    
    private string field_077Field;
    
    private string field_078Field;
    
    private string field_079Field;
    
    private string field_080Field;
    
    private string field_081Field;
    
    private string field_082Field;
    
    private string field_083Field;
    
    private string field_084Field;
    
    private string field_085Field;
    
    private string field_086Field;
    
    private string field_087Field;
    
    private string field_088Field;
    
    private string field_089Field;
    
    private string field_090Field;
    
    private string field_091Field;
    
    private string field_095Field;
    
    private string field_097Field;
    
    private string field_098Field;
    
    private string field_100Field;
    
    private string field_101Field;
    
    private string field_102Field;
    
    private string field_103Field;
    
    private string field_118Field;
    
    private string field_119Field;
    
    private string field_123Field;
    
    private string field_127_002Field;
    
    private string field_127_003Field;
    
    private string field_127_004Field;
    
    private string field_127_005Field;
    
    private string field_127_006Field;
    
    private string field_127_007Field;
    
    private string field_127_008Field;
    
    private string field_127_009Field;
    
    private string field_127_010Field;
    
    private string field_127_011Field;
    
    private string field_127_012Field;
    
    private string field_127_013Field;
    
    private string field_127_014Field;
    
    private string field_127_015Field;
    
    private string field_127_016Field;
    
    private string field_127_017Field;
    
    private string field_127_018Field;
    
    private string field_127_019Field;
    
    private string field_127_020Field;
    
    private string field_127_021Field;
    
    private string field_127_022Field;
    
    private string field_127_023Field;
    
    private string field_127_024Field;
    
    private string field_127_025Field;
    
    private string field_127_026Field;
    
    private string field_127_027Field;
    
    private string field_127_028Field;
    
    private string field_127_029Field;
    
    private string field_127_030Field;
    
    private string field_127_031Field;
    
    private string field_127_032Field;
    
    private string field_127_033Field;
    
    private string field_127_034Field;
    
    private string field_127_035Field;
    
    private string field_127_039Field;
    
    /// <remarks/>
    public string Field_002 {
        get {
            return this.field_002Field;
        }
        set {
            this.field_002Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_003 {
        get {
            return this.field_003Field;
        }
        set {
            this.field_003Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_004 {
        get {
            return this.field_004Field;
        }
        set {
            this.field_004Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_005 {
        get {
            return this.field_005Field;
        }
        set {
            this.field_005Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_007 {
        get {
            return this.field_007Field;
        }
        set {
            this.field_007Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_009 {
        get {
            return this.field_009Field;
        }
        set {
            this.field_009Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_011 {
        get {
            return this.field_011Field;
        }
        set {
            this.field_011Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_012 {
        get {
            return this.field_012Field;
        }
        set {
            this.field_012Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_013 {
        get {
            return this.field_013Field;
        }
        set {
            this.field_013Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_014 {
        get {
            return this.field_014Field;
        }
        set {
            this.field_014Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_015 {
        get {
            return this.field_015Field;
        }
        set {
            this.field_015Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_016 {
        get {
            return this.field_016Field;
        }
        set {
            this.field_016Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_018 {
        get {
            return this.field_018Field;
        }
        set {
            this.field_018Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_022 {
        get {
            return this.field_022Field;
        }
        set {
            this.field_022Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_023 {
        get {
            return this.field_023Field;
        }
        set {
            this.field_023Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_025 {
        get {
            return this.field_025Field;
        }
        set {
            this.field_025Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_026 {
        get {
            return this.field_026Field;
        }
        set {
            this.field_026Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_027 {
        get {
            return this.field_027Field;
        }
        set {
            this.field_027Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_028 {
        get {
            return this.field_028Field;
        }
        set {
            this.field_028Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_029 {
        get {
            return this.field_029Field;
        }
        set {
            this.field_029Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_030 {
        get {
            return this.field_030Field;
        }
        set {
            this.field_030Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_031 {
        get {
            return this.field_031Field;
        }
        set {
            this.field_031Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_032 {
        get {
            return this.field_032Field;
        }
        set {
            this.field_032Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_033 {
        get {
            return this.field_033Field;
        }
        set {
            this.field_033Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_035 {
        get {
            return this.field_035Field;
        }
        set {
            this.field_035Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_037 {
        get {
            return this.field_037Field;
        }
        set {
            this.field_037Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_038 {
        get {
            return this.field_038Field;
        }
        set {
            this.field_038Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_039 {
        get {
            return this.field_039Field;
        }
        set {
            this.field_039Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_040 {
        get {
            return this.field_040Field;
        }
        set {
            this.field_040Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_041 {
        get {
            return this.field_041Field;
        }
        set {
            this.field_041Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_042 {
        get {
            return this.field_042Field;
        }
        set {
            this.field_042Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_043 {
        get {
            return this.field_043Field;
        }
        set {
            this.field_043Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_044 {
        get {
            return this.field_044Field;
        }
        set {
            this.field_044Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_045 {
        get {
            return this.field_045Field;
        }
        set {
            this.field_045Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_048 {
        get {
            return this.field_048Field;
        }
        set {
            this.field_048Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_049 {
        get {
            return this.field_049Field;
        }
        set {
            this.field_049Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_050 {
        get {
            return this.field_050Field;
        }
        set {
            this.field_050Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_052 {
        get {
            return this.field_052Field;
        }
        set {
            this.field_052Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_053 {
        get {
            return this.field_053Field;
        }
        set {
            this.field_053Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_054 {
        get {
            return this.field_054Field;
        }
        set {
            this.field_054Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_056 {
        get {
            return this.field_056Field;
        }
        set {
            this.field_056Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_057 {
        get {
            return this.field_057Field;
        }
        set {
            this.field_057Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_058 {
        get {
            return this.field_058Field;
        }
        set {
            this.field_058Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_059 {
        get {
            return this.field_059Field;
        }
        set {
            this.field_059Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_066 {
        get {
            return this.field_066Field;
        }
        set {
            this.field_066Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_067 {
        get {
            return this.field_067Field;
        }
        set {
            this.field_067Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_070 {
        get {
            return this.field_070Field;
        }
        set {
            this.field_070Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_073 {
        get {
            return this.field_073Field;
        }
        set {
            this.field_073Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_074 {
        get {
            return this.field_074Field;
        }
        set {
            this.field_074Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_075 {
        get {
            return this.field_075Field;
        }
        set {
            this.field_075Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_076 {
        get {
            return this.field_076Field;
        }
        set {
            this.field_076Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_077 {
        get {
            return this.field_077Field;
        }
        set {
            this.field_077Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_078 {
        get {
            return this.field_078Field;
        }
        set {
            this.field_078Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_079 {
        get {
            return this.field_079Field;
        }
        set {
            this.field_079Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_080 {
        get {
            return this.field_080Field;
        }
        set {
            this.field_080Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_081 {
        get {
            return this.field_081Field;
        }
        set {
            this.field_081Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_082 {
        get {
            return this.field_082Field;
        }
        set {
            this.field_082Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_083 {
        get {
            return this.field_083Field;
        }
        set {
            this.field_083Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_084 {
        get {
            return this.field_084Field;
        }
        set {
            this.field_084Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_085 {
        get {
            return this.field_085Field;
        }
        set {
            this.field_085Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_086 {
        get {
            return this.field_086Field;
        }
        set {
            this.field_086Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_087 {
        get {
            return this.field_087Field;
        }
        set {
            this.field_087Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_088 {
        get {
            return this.field_088Field;
        }
        set {
            this.field_088Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_089 {
        get {
            return this.field_089Field;
        }
        set {
            this.field_089Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_090 {
        get {
            return this.field_090Field;
        }
        set {
            this.field_090Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_091 {
        get {
            return this.field_091Field;
        }
        set {
            this.field_091Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_095 {
        get {
            return this.field_095Field;
        }
        set {
            this.field_095Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_097 {
        get {
            return this.field_097Field;
        }
        set {
            this.field_097Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_098 {
        get {
            return this.field_098Field;
        }
        set {
            this.field_098Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_100 {
        get {
            return this.field_100Field;
        }
        set {
            this.field_100Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_101 {
        get {
            return this.field_101Field;
        }
        set {
            this.field_101Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_102 {
        get {
            return this.field_102Field;
        }
        set {
            this.field_102Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_103 {
        get {
            return this.field_103Field;
        }
        set {
            this.field_103Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_118 {
        get {
            return this.field_118Field;
        }
        set {
            this.field_118Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_119 {
        get {
            return this.field_119Field;
        }
        set {
            this.field_119Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_123 {
        get {
            return this.field_123Field;
        }
        set {
            this.field_123Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_002 {
        get {
            return this.field_127_002Field;
        }
        set {
            this.field_127_002Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_003 {
        get {
            return this.field_127_003Field;
        }
        set {
            this.field_127_003Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_004 {
        get {
            return this.field_127_004Field;
        }
        set {
            this.field_127_004Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_005 {
        get {
            return this.field_127_005Field;
        }
        set {
            this.field_127_005Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_006 {
        get {
            return this.field_127_006Field;
        }
        set {
            this.field_127_006Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_007 {
        get {
            return this.field_127_007Field;
        }
        set {
            this.field_127_007Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_008 {
        get {
            return this.field_127_008Field;
        }
        set {
            this.field_127_008Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_009 {
        get {
            return this.field_127_009Field;
        }
        set {
            this.field_127_009Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_010 {
        get {
            return this.field_127_010Field;
        }
        set {
            this.field_127_010Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_011 {
        get {
            return this.field_127_011Field;
        }
        set {
            this.field_127_011Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_012 {
        get {
            return this.field_127_012Field;
        }
        set {
            this.field_127_012Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_013 {
        get {
            return this.field_127_013Field;
        }
        set {
            this.field_127_013Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_014 {
        get {
            return this.field_127_014Field;
        }
        set {
            this.field_127_014Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_015 {
        get {
            return this.field_127_015Field;
        }
        set {
            this.field_127_015Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_016 {
        get {
            return this.field_127_016Field;
        }
        set {
            this.field_127_016Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_017 {
        get {
            return this.field_127_017Field;
        }
        set {
            this.field_127_017Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_018 {
        get {
            return this.field_127_018Field;
        }
        set {
            this.field_127_018Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_019 {
        get {
            return this.field_127_019Field;
        }
        set {
            this.field_127_019Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_020 {
        get {
            return this.field_127_020Field;
        }
        set {
            this.field_127_020Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_021 {
        get {
            return this.field_127_021Field;
        }
        set {
            this.field_127_021Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_022 {
        get {
            return this.field_127_022Field;
        }
        set {
            this.field_127_022Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_023 {
        get {
            return this.field_127_023Field;
        }
        set {
            this.field_127_023Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_024 {
        get {
            return this.field_127_024Field;
        }
        set {
            this.field_127_024Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_025 {
        get {
            return this.field_127_025Field;
        }
        set {
            this.field_127_025Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_026 {
        get {
            return this.field_127_026Field;
        }
        set {
            this.field_127_026Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_027 {
        get {
            return this.field_127_027Field;
        }
        set {
            this.field_127_027Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_028 {
        get {
            return this.field_127_028Field;
        }
        set {
            this.field_127_028Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_029 {
        get {
            return this.field_127_029Field;
        }
        set {
            this.field_127_029Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_030 {
        get {
            return this.field_127_030Field;
        }
        set {
            this.field_127_030Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_031 {
        get {
            return this.field_127_031Field;
        }
        set {
            this.field_127_031Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_032 {
        get {
            return this.field_127_032Field;
        }
        set {
            this.field_127_032Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_033 {
        get {
            return this.field_127_033Field;
        }
        set {
            this.field_127_033Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_034 {
        get {
            return this.field_127_034Field;
        }
        set {
            this.field_127_034Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_035 {
        get {
            return this.field_127_035Field;
        }
        set {
            this.field_127_035Field = value;
        }
    }
    
    /// <remarks/>
    public string Field_127_039 {
        get {
            return this.field_127_039Field;
        }
        set {
            this.field_127_039Field = value;
        }
    }
}
