//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", ConfigurationName="FCUBSRTService.FCUBSRTServiceSEI")]
    public interface FCUBSRTServiceSEI {
        
        // CODEGEN: Generating message contract since the operation AuthorizeTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.AuthorizeTransactionResponse AuthorizeTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.AuthorizeTransactionRequest request);
        
        // CODEGEN: Generating message contract since the operation CreateTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.CreateTransactionResponse CreateTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.CreateTransactionRequest request);
        
        // CODEGEN: Generating message contract since the operation QueryRTProduct is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryRTProductResponse QueryRTProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryRTProductRequest request);
        
        // CODEGEN: Generating message contract since the operation QueryTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryTransactionResponse QueryTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryTransactionRequest request);
        
        // CODEGEN: Generating message contract since the operation ReverseTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.ReverseTransactionResponse ReverseTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.ReverseTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string AuthorizeTransaction;
        
        public AuthorizeTransactionRequest() {
        }
        
        public AuthorizeTransactionRequest(string AuthorizeTransaction) {
            this.AuthorizeTransaction = AuthorizeTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeTransactionResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string AuthorizeTransactionResponse1;
        
        public AuthorizeTransactionResponse() {
        }
        
        public AuthorizeTransactionResponse(string AuthorizeTransactionResponse1) {
            this.AuthorizeTransactionResponse1 = AuthorizeTransactionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string CreateTransaction;
        
        public CreateTransactionRequest() {
        }
        
        public CreateTransactionRequest(string CreateTransaction) {
            this.CreateTransaction = CreateTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTransactionResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string CreateTransactionResponse1;
        
        public CreateTransactionResponse() {
        }
        
        public CreateTransactionResponse(string CreateTransactionResponse1) {
            this.CreateTransactionResponse1 = CreateTransactionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRTProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string QueryRTProduct;
        
        public QueryRTProductRequest() {
        }
        
        public QueryRTProductRequest(string QueryRTProduct) {
            this.QueryRTProduct = QueryRTProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryRTProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryRTProductResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string QueryRTProductResponse1;
        
        public QueryRTProductResponse() {
        }
        
        public QueryRTProductResponse(string QueryRTProductResponse1) {
            this.QueryRTProductResponse1 = QueryRTProductResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string QueryTransaction;
        
        public QueryTransactionRequest() {
        }
        
        public QueryTransactionRequest(string QueryTransaction) {
            this.QueryTransaction = QueryTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryTransactionResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string QueryTransactionResponse1;
        
        public QueryTransactionResponse() {
        }
        
        public QueryTransactionResponse(string QueryTransactionResponse1) {
            this.QueryTransactionResponse1 = QueryTransactionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string ReverseTransaction;
        
        public ReverseTransactionRequest() {
        }
        
        public ReverseTransactionRequest(string ReverseTransaction) {
            this.ReverseTransaction = ReverseTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseTransactionResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string ReverseTransactionResponse1;
        
        public ReverseTransactionResponse() {
        }
        
        public ReverseTransactionResponse(string ReverseTransactionResponse1) {
            this.ReverseTransactionResponse1 = ReverseTransactionResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FCUBSRTServiceSEIChannel : e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FCUBSRTServiceSEIClient : System.ServiceModel.ClientBase<e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI>, e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI {
        
        public FCUBSRTServiceSEIClient() {
        }
        
        public FCUBSRTServiceSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FCUBSRTServiceSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCUBSRTServiceSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCUBSRTServiceSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.AuthorizeTransactionResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI.AuthorizeTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.AuthorizeTransactionRequest request) {
            return base.Channel.AuthorizeTransaction(request);
        }
        
        public string AuthorizeTransaction(string AuthorizeTransaction1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.AuthorizeTransactionRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.AuthorizeTransactionRequest();
            inValue.AuthorizeTransaction = AuthorizeTransaction1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.AuthorizeTransactionResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI)(this)).AuthorizeTransaction(inValue);
            return retVal.AuthorizeTransactionResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.CreateTransactionResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI.CreateTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.CreateTransactionRequest request) {
            return base.Channel.CreateTransaction(request);
        }
        
        public string CreateTransaction(string CreateTransaction1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.CreateTransactionRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.CreateTransactionRequest();
            inValue.CreateTransaction = CreateTransaction1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.CreateTransactionResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI)(this)).CreateTransaction(inValue);
            return retVal.CreateTransactionResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryRTProductResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI.QueryRTProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryRTProductRequest request) {
            return base.Channel.QueryRTProduct(request);
        }
        
        public string QueryRTProduct(string QueryRTProduct1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryRTProductRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryRTProductRequest();
            inValue.QueryRTProduct = QueryRTProduct1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryRTProductResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI)(this)).QueryRTProduct(inValue);
            return retVal.QueryRTProductResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryTransactionResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI.QueryTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryTransactionRequest request) {
            return base.Channel.QueryTransaction(request);
        }
        
        public string QueryTransaction(string QueryTransaction1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryTransactionRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryTransactionRequest();
            inValue.QueryTransaction = QueryTransaction1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.QueryTransactionResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI)(this)).QueryTransaction(inValue);
            return retVal.QueryTransactionResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.ReverseTransactionResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI.ReverseTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.ReverseTransactionRequest request) {
            return base.Channel.ReverseTransaction(request);
        }
        
        public string ReverseTransaction(string ReverseTransaction1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.ReverseTransactionRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.ReverseTransactionRequest();
            inValue.ReverseTransaction = ReverseTransaction1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.ReverseTransactionResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSRTService.FCUBSRTServiceSEI)(this)).ReverseTransaction(inValue);
            return retVal.ReverseTransactionResponse1;
        }
    }
}
