//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", ConfigurationName="FCUBSUPService.FCUBSUPServiceSEI")]
    public interface FCUBSUPServiceSEI {
        
        // CODEGEN: Generating message contract since the operation CreateUPTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.CreateUPTransactionResponse CreateUPTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.CreateUPTransactionRequest request);
        
        // CODEGEN: Generating message contract since the operation QueryUPTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.QueryUPTransactionResponse QueryUPTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.QueryUPTransactionRequest request);
        
        // CODEGEN: Generating message contract since the operation ReverseUPTransaction is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.ReverseUPTransactionResponse ReverseUPTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.ReverseUPTransactionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUPTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string CreateUPTransaction;
        
        public CreateUPTransactionRequest() {
        }
        
        public CreateUPTransactionRequest(string CreateUPTransaction) {
            this.CreateUPTransaction = CreateUPTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateUPTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateUPTransactionResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string CreateUPTransactionResponse1;
        
        public CreateUPTransactionResponse() {
        }
        
        public CreateUPTransactionResponse(string CreateUPTransactionResponse1) {
            this.CreateUPTransactionResponse1 = CreateUPTransactionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUPTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string QueryUPTransaction;
        
        public QueryUPTransactionRequest() {
        }
        
        public QueryUPTransactionRequest(string QueryUPTransaction) {
            this.QueryUPTransaction = QueryUPTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryUPTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryUPTransactionResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string QueryUPTransactionResponse1;
        
        public QueryUPTransactionResponse() {
        }
        
        public QueryUPTransactionResponse(string QueryUPTransactionResponse1) {
            this.QueryUPTransactionResponse1 = QueryUPTransactionResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseUPTransactionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string ReverseUPTransaction;
        
        public ReverseUPTransactionRequest() {
        }
        
        public ReverseUPTransactionRequest(string ReverseUPTransaction) {
            this.ReverseUPTransaction = ReverseUPTransaction;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseUPTransactionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseUPTransactionResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string ReverseUPTransactionResponse1;
        
        public ReverseUPTransactionResponse() {
        }
        
        public ReverseUPTransactionResponse(string ReverseUPTransactionResponse1) {
            this.ReverseUPTransactionResponse1 = ReverseUPTransactionResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FCUBSUPServiceSEIChannel : e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.FCUBSUPServiceSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FCUBSUPServiceSEIClient : System.ServiceModel.ClientBase<e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.FCUBSUPServiceSEI>, e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.FCUBSUPServiceSEI {
        
        public FCUBSUPServiceSEIClient() {
        }
        
        public FCUBSUPServiceSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FCUBSUPServiceSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCUBSUPServiceSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCUBSUPServiceSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.CreateUPTransactionResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.FCUBSUPServiceSEI.CreateUPTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.CreateUPTransactionRequest request) {
            return base.Channel.CreateUPTransaction(request);
        }
        
        public string CreateUPTransaction(string CreateUPTransaction1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.CreateUPTransactionRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.CreateUPTransactionRequest();
            inValue.CreateUPTransaction = CreateUPTransaction1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.CreateUPTransactionResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.FCUBSUPServiceSEI)(this)).CreateUPTransaction(inValue);
            return retVal.CreateUPTransactionResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.QueryUPTransactionResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.FCUBSUPServiceSEI.QueryUPTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.QueryUPTransactionRequest request) {
            return base.Channel.QueryUPTransaction(request);
        }
        
        public string QueryUPTransaction(string QueryUPTransaction1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.QueryUPTransactionRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.QueryUPTransactionRequest();
            inValue.QueryUPTransaction = QueryUPTransaction1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.QueryUPTransactionResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.FCUBSUPServiceSEI)(this)).QueryUPTransaction(inValue);
            return retVal.QueryUPTransactionResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.ReverseUPTransactionResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.FCUBSUPServiceSEI.ReverseUPTransaction(e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.ReverseUPTransactionRequest request) {
            return base.Channel.ReverseUPTransaction(request);
        }
        
        public string ReverseUPTransaction(string ReverseUPTransaction1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.ReverseUPTransactionRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.ReverseUPTransactionRequest();
            inValue.ReverseUPTransaction = ReverseUPTransaction1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.ReverseUPTransactionResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSUPService.FCUBSUPServiceSEI)(this)).ReverseUPTransaction(inValue);
            return retVal.ReverseUPTransactionResponse1;
        }
    }
}
