//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", ConfigurationName="FCUBSFTService.FCUBSFTServiceSEI")]
    public interface FCUBSFTServiceSEI {
        
        // CODEGEN: Generating message contract since the operation AmendFTContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AmendFTContractResponse AmendFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AmendFTContractRequest request);
        
        // CODEGEN: Generating message contract since the operation AuthorizeFTContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeFTContractResponse AuthorizeFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeFTContractRequest request);
        
        // CODEGEN: Generating message contract since the operation AuthorizeProduct is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeProductResponse AuthorizeProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeProductRequest request);
        
        // CODEGEN: Generating message contract since the operation CancelFTContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CancelFTContractResponse CancelFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CancelFTContractRequest request);
        
        // CODEGEN: Generating message contract since the operation CreateFTContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateFTContractResponse CreateFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateFTContractRequest request);
        
        // CODEGEN: Generating message contract since the operation CreateProduct is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateProductResponse CreateProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateProductRequest request);
        
        // CODEGEN: Generating message contract since the operation DeleteFTContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteFTContractResponse DeleteFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteFTContractRequest request);
        
        // CODEGEN: Generating message contract since the operation DeleteProduct is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteProductResponse DeleteProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteProductRequest request);
        
        // CODEGEN: Generating message contract since the operation LiquidateFTContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.LiquidateFTContractResponse LiquidateFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.LiquidateFTContractRequest request);
        
        // CODEGEN: Generating message contract since the operation ModifyProduct is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ModifyProductResponse ModifyProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ModifyProductRequest request);
        
        // CODEGEN: Generating message contract since the operation MsggenFTContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.MsggenFTContractResponse MsggenFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.MsggenFTContractRequest request);
        
        // CODEGEN: Generating message contract since the operation QueryFTContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryFTContractResponse QueryFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryFTContractRequest request);
        
        // CODEGEN: Generating message contract since the operation QueryProduct is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryProductResponse QueryProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryProductRequest request);
        
        // CODEGEN: Generating message contract since the operation ReassignFTContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReassignFTContractResponse ReassignFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReassignFTContractRequest request);
        
        // CODEGEN: Generating message contract since the operation ReverseFTContract is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReverseFTContractResponse ReverseFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReverseFTContractRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AmendFTContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string AmendFTContract;
        
        public AmendFTContractRequest() {
        }
        
        public AmendFTContractRequest(string AmendFTContract) {
            this.AmendFTContract = AmendFTContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AmendFTContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AmendFTContractResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string AmendFTContractResponse1;
        
        public AmendFTContractResponse() {
        }
        
        public AmendFTContractResponse(string AmendFTContractResponse1) {
            this.AmendFTContractResponse1 = AmendFTContractResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeFTContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string AuthorizeFTContract;
        
        public AuthorizeFTContractRequest() {
        }
        
        public AuthorizeFTContractRequest(string AuthorizeFTContract) {
            this.AuthorizeFTContract = AuthorizeFTContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeFTContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeFTContractResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string AuthorizeFTContractResponse1;
        
        public AuthorizeFTContractResponse() {
        }
        
        public AuthorizeFTContractResponse(string AuthorizeFTContractResponse1) {
            this.AuthorizeFTContractResponse1 = AuthorizeFTContractResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string AuthorizeProduct;
        
        public AuthorizeProductRequest() {
        }
        
        public AuthorizeProductRequest(string AuthorizeProduct) {
            this.AuthorizeProduct = AuthorizeProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AuthorizeProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AuthorizeProductResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string AuthorizeProductResponse1;
        
        public AuthorizeProductResponse() {
        }
        
        public AuthorizeProductResponse(string AuthorizeProductResponse1) {
            this.AuthorizeProductResponse1 = AuthorizeProductResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelFTContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string CancelFTContract;
        
        public CancelFTContractRequest() {
        }
        
        public CancelFTContractRequest(string CancelFTContract) {
            this.CancelFTContract = CancelFTContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CancelFTContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CancelFTContractResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string CancelFTContractResponse1;
        
        public CancelFTContractResponse() {
        }
        
        public CancelFTContractResponse(string CancelFTContractResponse1) {
            this.CancelFTContractResponse1 = CancelFTContractResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFTContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string CreateFTContract;
        
        public CreateFTContractRequest() {
        }
        
        public CreateFTContractRequest(string CreateFTContract) {
            this.CreateFTContract = CreateFTContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateFTContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateFTContractResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string CreateFTContractResponse1;
        
        public CreateFTContractResponse() {
        }
        
        public CreateFTContractResponse(string CreateFTContractResponse1) {
            this.CreateFTContractResponse1 = CreateFTContractResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string CreateProduct;
        
        public CreateProductRequest() {
        }
        
        public CreateProductRequest(string CreateProduct) {
            this.CreateProduct = CreateProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateProductResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string CreateProductResponse1;
        
        public CreateProductResponse() {
        }
        
        public CreateProductResponse(string CreateProductResponse1) {
            this.CreateProductResponse1 = CreateProductResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFTContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string DeleteFTContract;
        
        public DeleteFTContractRequest() {
        }
        
        public DeleteFTContractRequest(string DeleteFTContract) {
            this.DeleteFTContract = DeleteFTContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteFTContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteFTContractResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string DeleteFTContractResponse1;
        
        public DeleteFTContractResponse() {
        }
        
        public DeleteFTContractResponse(string DeleteFTContractResponse1) {
            this.DeleteFTContractResponse1 = DeleteFTContractResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string DeleteProduct;
        
        public DeleteProductRequest() {
        }
        
        public DeleteProductRequest(string DeleteProduct) {
            this.DeleteProduct = DeleteProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteProductResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string DeleteProductResponse1;
        
        public DeleteProductResponse() {
        }
        
        public DeleteProductResponse(string DeleteProductResponse1) {
            this.DeleteProductResponse1 = DeleteProductResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LiquidateFTContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string LiquidateFTContract;
        
        public LiquidateFTContractRequest() {
        }
        
        public LiquidateFTContractRequest(string LiquidateFTContract) {
            this.LiquidateFTContract = LiquidateFTContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LiquidateFTContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LiquidateFTContractResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string LiquidateFTContractResponse1;
        
        public LiquidateFTContractResponse() {
        }
        
        public LiquidateFTContractResponse(string LiquidateFTContractResponse1) {
            this.LiquidateFTContractResponse1 = LiquidateFTContractResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string ModifyProduct;
        
        public ModifyProductRequest() {
        }
        
        public ModifyProductRequest(string ModifyProduct) {
            this.ModifyProduct = ModifyProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ModifyProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ModifyProductResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string ModifyProductResponse1;
        
        public ModifyProductResponse() {
        }
        
        public ModifyProductResponse(string ModifyProductResponse1) {
            this.ModifyProductResponse1 = ModifyProductResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsggenFTContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MsggenFTContract;
        
        public MsggenFTContractRequest() {
        }
        
        public MsggenFTContractRequest(string MsggenFTContract) {
            this.MsggenFTContract = MsggenFTContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class MsggenFTContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="MsggenFTContractResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string MsggenFTContractResponse1;
        
        public MsggenFTContractResponse() {
        }
        
        public MsggenFTContractResponse(string MsggenFTContractResponse1) {
            this.MsggenFTContractResponse1 = MsggenFTContractResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryFTContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string QueryFTContract;
        
        public QueryFTContractRequest() {
        }
        
        public QueryFTContractRequest(string QueryFTContract) {
            this.QueryFTContract = QueryFTContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryFTContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryFTContractResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string QueryFTContractResponse1;
        
        public QueryFTContractResponse() {
        }
        
        public QueryFTContractResponse(string QueryFTContractResponse1) {
            this.QueryFTContractResponse1 = QueryFTContractResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryProductRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string QueryProduct;
        
        public QueryProductRequest() {
        }
        
        public QueryProductRequest(string QueryProduct) {
            this.QueryProduct = QueryProduct;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class QueryProductResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="QueryProductResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string QueryProductResponse1;
        
        public QueryProductResponse() {
        }
        
        public QueryProductResponse(string QueryProductResponse1) {
            this.QueryProductResponse1 = QueryProductResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReassignFTContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string ReassignFTContract;
        
        public ReassignFTContractRequest() {
        }
        
        public ReassignFTContractRequest(string ReassignFTContract) {
            this.ReassignFTContract = ReassignFTContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReassignFTContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReassignFTContractResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string ReassignFTContractResponse1;
        
        public ReassignFTContractResponse() {
        }
        
        public ReassignFTContractResponse(string ReassignFTContractResponse1) {
            this.ReassignFTContractResponse1 = ReassignFTContractResponse1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseFTContractRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string ReverseFTContract;
        
        public ReverseFTContractRequest() {
        }
        
        public ReverseFTContractRequest(string ReverseFTContract) {
            this.ReverseFTContract = ReverseFTContract;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReverseFTContractResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReverseFTContractResponse", Namespace="http://types.ws.gw.fcubs.iflex.com", Order=0)]
        public string ReverseFTContractResponse1;
        
        public ReverseFTContractResponse() {
        }
        
        public ReverseFTContractResponse(string ReverseFTContractResponse1) {
            this.ReverseFTContractResponse1 = ReverseFTContractResponse1;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FCUBSFTServiceSEIChannel : e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FCUBSFTServiceSEIClient : System.ServiceModel.ClientBase<e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI>, e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI {
        
        public FCUBSFTServiceSEIClient() {
        }
        
        public FCUBSFTServiceSEIClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FCUBSFTServiceSEIClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCUBSFTServiceSEIClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FCUBSFTServiceSEIClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AmendFTContractResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.AmendFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AmendFTContractRequest request) {
            return base.Channel.AmendFTContract(request);
        }
        
        public string AmendFTContract(string AmendFTContract1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AmendFTContractRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AmendFTContractRequest();
            inValue.AmendFTContract = AmendFTContract1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AmendFTContractResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).AmendFTContract(inValue);
            return retVal.AmendFTContractResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeFTContractResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.AuthorizeFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeFTContractRequest request) {
            return base.Channel.AuthorizeFTContract(request);
        }
        
        public string AuthorizeFTContract(string AuthorizeFTContract1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeFTContractRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeFTContractRequest();
            inValue.AuthorizeFTContract = AuthorizeFTContract1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeFTContractResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).AuthorizeFTContract(inValue);
            return retVal.AuthorizeFTContractResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeProductResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.AuthorizeProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeProductRequest request) {
            return base.Channel.AuthorizeProduct(request);
        }
        
        public string AuthorizeProduct(string AuthorizeProduct1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeProductRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeProductRequest();
            inValue.AuthorizeProduct = AuthorizeProduct1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.AuthorizeProductResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).AuthorizeProduct(inValue);
            return retVal.AuthorizeProductResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CancelFTContractResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.CancelFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CancelFTContractRequest request) {
            return base.Channel.CancelFTContract(request);
        }
        
        public string CancelFTContract(string CancelFTContract1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CancelFTContractRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CancelFTContractRequest();
            inValue.CancelFTContract = CancelFTContract1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CancelFTContractResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).CancelFTContract(inValue);
            return retVal.CancelFTContractResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateFTContractResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.CreateFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateFTContractRequest request) {
            return base.Channel.CreateFTContract(request);
        }
        
        public string CreateFTContract(string CreateFTContract1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateFTContractRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateFTContractRequest();
            inValue.CreateFTContract = CreateFTContract1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateFTContractResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).CreateFTContract(inValue);
            return retVal.CreateFTContractResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateProductResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.CreateProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateProductRequest request) {
            return base.Channel.CreateProduct(request);
        }
        
        public string CreateProduct(string CreateProduct1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateProductRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateProductRequest();
            inValue.CreateProduct = CreateProduct1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.CreateProductResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).CreateProduct(inValue);
            return retVal.CreateProductResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteFTContractResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.DeleteFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteFTContractRequest request) {
            return base.Channel.DeleteFTContract(request);
        }
        
        public string DeleteFTContract(string DeleteFTContract1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteFTContractRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteFTContractRequest();
            inValue.DeleteFTContract = DeleteFTContract1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteFTContractResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).DeleteFTContract(inValue);
            return retVal.DeleteFTContractResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteProductResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.DeleteProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteProductRequest request) {
            return base.Channel.DeleteProduct(request);
        }
        
        public string DeleteProduct(string DeleteProduct1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteProductRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteProductRequest();
            inValue.DeleteProduct = DeleteProduct1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.DeleteProductResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).DeleteProduct(inValue);
            return retVal.DeleteProductResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.LiquidateFTContractResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.LiquidateFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.LiquidateFTContractRequest request) {
            return base.Channel.LiquidateFTContract(request);
        }
        
        public string LiquidateFTContract(string LiquidateFTContract1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.LiquidateFTContractRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.LiquidateFTContractRequest();
            inValue.LiquidateFTContract = LiquidateFTContract1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.LiquidateFTContractResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).LiquidateFTContract(inValue);
            return retVal.LiquidateFTContractResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ModifyProductResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.ModifyProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ModifyProductRequest request) {
            return base.Channel.ModifyProduct(request);
        }
        
        public string ModifyProduct(string ModifyProduct1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ModifyProductRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ModifyProductRequest();
            inValue.ModifyProduct = ModifyProduct1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ModifyProductResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).ModifyProduct(inValue);
            return retVal.ModifyProductResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.MsggenFTContractResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.MsggenFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.MsggenFTContractRequest request) {
            return base.Channel.MsggenFTContract(request);
        }
        
        public string MsggenFTContract(string MsggenFTContract1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.MsggenFTContractRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.MsggenFTContractRequest();
            inValue.MsggenFTContract = MsggenFTContract1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.MsggenFTContractResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).MsggenFTContract(inValue);
            return retVal.MsggenFTContractResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryFTContractResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.QueryFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryFTContractRequest request) {
            return base.Channel.QueryFTContract(request);
        }
        
        public string QueryFTContract(string QueryFTContract1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryFTContractRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryFTContractRequest();
            inValue.QueryFTContract = QueryFTContract1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryFTContractResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).QueryFTContract(inValue);
            return retVal.QueryFTContractResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryProductResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.QueryProduct(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryProductRequest request) {
            return base.Channel.QueryProduct(request);
        }
        
        public string QueryProduct(string QueryProduct1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryProductRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryProductRequest();
            inValue.QueryProduct = QueryProduct1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.QueryProductResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).QueryProduct(inValue);
            return retVal.QueryProductResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReassignFTContractResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.ReassignFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReassignFTContractRequest request) {
            return base.Channel.ReassignFTContract(request);
        }
        
        public string ReassignFTContract(string ReassignFTContract1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReassignFTContractRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReassignFTContractRequest();
            inValue.ReassignFTContract = ReassignFTContract1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReassignFTContractResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).ReassignFTContract(inValue);
            return retVal.ReassignFTContractResponse1;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReverseFTContractResponse e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI.ReverseFTContract(e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReverseFTContractRequest request) {
            return base.Channel.ReverseFTContract(request);
        }
        
        public string ReverseFTContract(string ReverseFTContract1) {
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReverseFTContractRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReverseFTContractRequest();
            inValue.ReverseFTContract = ReverseFTContract1;
            e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.ReverseFTContractResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.FCUBSFTService.FCUBSFTServiceSEI)(this)).ReverseFTContract(inValue);
            return retVal.ReverseFTContractResponse1;
        }
    }
}
