//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge {
    using System.Data;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/", ConfigurationName="Finacle_Bridge.Finacle_BridgeSoap")]
    public interface Finacle_BridgeSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/CheckStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int CheckStatus();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/generateRandom", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string generateRandom();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/autoRegister", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.registration_Response autoRegister(string userID, string userPassword, string mobileNumber, string accountNumber, string accountName, string currencyCode, string chargeType, string Product, string Provider, string registationCRUD_Action, string IDNumber, string IDType_IorP, string IDType_LorF);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/autoRegister_Account", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.registration_Response autoRegister_Account(string userID, string userPassword, string mobileNumber, string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/autoRegister_Card_Account", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.registration_Response autoRegister_Card_Account(string userID, string userPassword, string mobileNumber, string cardNumber, string accountNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/autoRegister_Card", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.registration_Response autoRegister_Card(string userID, string userPassword, string mobileNumber, string cardNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/Query_Payment_Status_ZeePay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.TrnStatus Query_Payment_Status_ZeePay(string channelID, string sourceReference, string originalTransactionID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/MarkUnMarkLien", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Account_Lien MarkUnMarkLien(string SR_UserID, string SR_Password, string channelID, string Param_AccountNo, string Param_Amount, string Param_Currency, string Param_BranchID, string Param_RequestUUID, string ParamMarkP_or_UnMarkN, string sourceSystem);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/PostToFinacle_ZeePay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_Response_Detail PostToFinacle_ZeePay(
                    string SR_UserID, 
                    string SR_Password, 
                    string Param1_channelId, 
                    string Param1_RequestUUID, 
                    string Parm1_ChannelRefNum, 
                    bool Parm1_ReversalFlag, 
                    string Parm1_OriginalChannelRefNum, 
                    string Parm1_TranAmount, 
                    string Parm1_TranCrncy, 
                    string Parm1_DrAcctNo, 
                    string Parm1_CrAcctNo, 
                    string Parm1_CrValueDate, 
                    string Parm1_DrBICCode, 
                    string Parm1_CrBICCode, 
                    string Parm1_DrAcctName, 
                    string Parm1_DrAcctAddress1, 
                    string Parm1_DrAcctAddress2, 
                    string Parm1_DrAcctAddress3, 
                    string Parm1_DrTranParticulars, 
                    string Parm1_DrTranRemarks1, 
                    string Parm1_DrTranRemarks2, 
                    string Parm1_CrTranParticulars, 
                    string Parm1_CrTranRemarks1, 
                    string Parm1_CrTranRemarks2, 
                    string Parm1_TranParticularsCodeDr, 
                    string Parm1_TranParticularsCodeCr, 
                    string Parm1_SourceChannel, 
                    string Parm1_DrForcePostFlag, 
                    string Parm1_CrAcctAddress1, 
                    string Parm1_CrAcctAddress2, 
                    string Parm1_CrAcctAddress3, 
                    string ExtraDetails);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/PostToEDMI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_Response_Detail PostToEDMI(
                    string SR_UserID, 
                    string SR_Password, 
                    string Param1_channelId, 
                    string Param1_RequestUUID, 
                    string Parm1_ChannelRefNum, 
                    bool Parm1_ReversalFlag, 
                    string Parm1_OriginalChannelRefNum, 
                    string Parm1_TranAmount, 
                    string Parm1_TranCrncy, 
                    string Parm1_DrAcctNo, 
                    string Parm1_CrAcctNo, 
                    string Parm1_CrValueDate, 
                    string Parm1_DrBICCode, 
                    string Parm1_CrBICCode, 
                    string Parm1_DrAcctName, 
                    string Parm1_DrAcctAddress1, 
                    string Parm1_DrTranParticulars, 
                    string Parm1_DrTranRemarks1, 
                    string Parm1_DrTranRemarks2, 
                    string Parm1_CrTranParticulars, 
                    string Parm1_CrTranRemarks1, 
                    string Parm1_CrTranRemarks2, 
                    string Parm1_TranParticularsCodeDr, 
                    string Parm1_TranParticularsCodeCr, 
                    string Parm1_SourceChannel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/ReverseTransaction_SCB", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Posting_Response ReverseTransaction_SCB(string XML_Ref_C, string ChannelRefNum_C, string Source_Channel, string Trn_ID, string AccountNo, double trnAmount, string TrnRemarks, bool usePseudoResponse, string TRANSACTION_TYPE);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/PostToFinacle", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_Response_Detail PostToFinacle(
                    string SR_UserID, 
                    string SR_Password, 
                    string Param1_channelId, 
                    string Param1_RequestUUID, 
                    string Parm1_ChannelRefNum, 
                    bool Parm1_ReversalFlag, 
                    string Parm1_OriginalChannelRefNum, 
                    string Parm1_TranAmount, 
                    string Parm1_TranCrncy, 
                    string Parm1_DrAcctNo, 
                    string Parm1_CrAcctNo, 
                    string Parm1_CrValueDate, 
                    string Parm1_DrBICCode, 
                    string Parm1_CrBICCode, 
                    string Parm1_DrAcctName, 
                    string Parm1_DrAcctAddress1, 
                    string Parm1_DrTranParticulars, 
                    string Parm1_DrTranRemarks1, 
                    string Parm1_DrTranRemarks2, 
                    string Parm1_CrTranParticulars, 
                    string Parm1_CrTranRemarks1, 
                    string Parm1_CrTranRemarks2, 
                    string Parm1_TranParticularsCodeDr, 
                    string Parm1_TranParticularsCodeCr, 
                    string Parm1_SourceChannel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/PostToFinacle_WithForcePostFlag", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_Response_Detail PostToFinacle_WithForcePostFlag(
                    string SR_UserID, 
                    string SR_Password, 
                    string Param1_channelId, 
                    string Param1_RequestUUID, 
                    string Parm1_ChannelRefNum, 
                    bool Parm1_ReversalFlag, 
                    string Parm1_OriginalChannelRefNum, 
                    string Parm1_TranAmount, 
                    string Parm1_TranCrncy, 
                    string Parm1_DrAcctNo, 
                    string Parm1_CrAcctNo, 
                    string Parm1_CrValueDate, 
                    string Parm1_DrBICCode, 
                    string Parm1_CrBICCode, 
                    string Parm1_DrAcctName, 
                    string Parm1_DrAcctAddress1, 
                    string Parm1_DrTranParticulars, 
                    string Parm1_DrTranRemarks1, 
                    string Parm1_DrTranRemarks2, 
                    string Parm1_CrTranParticulars, 
                    string Parm1_CrTranRemarks1, 
                    string Parm1_CrTranRemarks2, 
                    string Parm1_TranParticularsCodeDr, 
                    string Parm1_TranParticularsCodeCr, 
                    string Parm1_SourceChannel, 
                    string Parm1_DrForcePostFlag);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/GetToken", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetToken(string userId, string password, string product, string NetworkProviderID, string telephoneNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/GetAccounts", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.AccountInfo GetAccounts(long tokenId, string telephoneNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/GetAccountBalance", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string GetAccountBalance(long tokenId, string telephoneNo, string accountNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/GetAccountStatement", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.StatementInfo GetAccountStatement(long tokenId, string telephoneNo, string accountNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/GetAccountStatement_ZeePay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.StatementInfo GetAccountStatement_ZeePay(string SR_UserID, string SR_Password, string accountNo, string UniqueReference);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/ResetPassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ResetPassword(string telephoneNo, string NetworkProviderID, string product, string oldPassword, string newPassword, string newPasswordConfirm);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/InternalTransfer", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InternalTransfer(long tokenId, string telephoneNo, string sourceAccountNo, string destinationAccountNo, string sourceReference, double transferAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/ThirdPartyPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ThirdPartyPayment(long tokenId, string telephoneNo, string sourceAccountNo, string destinationAccountNo, string destinationSWIFTCode, string sourceReference, string beneficiaryName, double paymentAmount, string Extra_Narrative1, string Extra_Narrative2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/BillPayment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string BillPayment(string userId, string password, long tokenId, string telephoneNo, string sourceAccountNo, string ServiceProviderID, string CustomerID, string sourceReference, string sourceNarrative, double paymentAmount, string Extra_Narrative1, string Extra_Narrative2);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/Get_BeneficiaryName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get_BeneficiaryName(string Beneficiary_Account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/Verify_BeneficiaryName", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Verify_BeneficiaryName(string ServiceProviderID, string CustomerID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/Get_Account_From_MobileNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string Get_Account_From_MobileNumber(string MobileNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/ZIPIT_SEND", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ZIPIT_SEND(string tokenId, string sourceAccount, string telephoneNo, string destinationInstitute, string destinationAccount, string sourceReference, long paymentAmount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/ZIPIT_SMART_REQUEST", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ZIPIT_SMART_REQUEST(string Api_Key, string User_Name, string Password, System.DateTime transmissionDate, string merchantCode, string channel, string acquiringInstID, string extendedTrantype);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/ZIPIT_SEND_KYC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ZIPIT_SEND_KYC(string tokenId, string sourceAccount, string telephoneNo, string destinationInstitute, string destinationAccount, string sourceReference, long paymentAmount, string IDNumber_KYC, string sourceAccount_KYC, string AccountName_KYC, string extraDetail_1, string extraDetail_2, string extraDetail_3);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/qry_FinTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Data.DataTable qry_FinTransaction(string AccountNo, string ChannelRefNum_C, string MobileNo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/ReverseTransaction_Post_First", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Posting_Response ReverseTransaction_Post_First(string XML_Ref_C, string ChannelRefNum_C, string Source_Channel, string Trn_ID, string AccountNo, string TrnRemarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/ReverseTransaction_ZeePay", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Posting_Response ReverseTransaction_ZeePay(string SR_UserID, string SR_Password, string XML_Ref_C, string ChannelRefNum, string Source_Channel, string Trn_ID, string AccountNo, string TrnRemarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/ReverseTransaction", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Posting_Response ReverseTransaction(string XML_Ref_C, string ChannelRefNum_C, string Source_Channel, string Trn_ID, string AccountNo, string TrnRemarks);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/Finacle_AccountEnquiry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Account_Enquiry_Detail Finacle_AccountEnquiry(string Param_Account, string Param_RequestUUID, bool UsePseudoResponse, string Parm_SourceChannel);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/ReverseZeePayTransaction_local", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_Response_Detail ReverseZeePayTransaction_local(string SR_UserID, string SR_Password, string channelId, string RequestUUID, string ChannelRefNum, string RequestXML);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class registration_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ExtensionDataObject extensionDataField;
        
        private bool registeredField;
        
        private string registrationMessageField;
        
        private string mobileNumberField;
        
        private string accountNumberField;
        
        private System.DateTime registrationTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
                this.RaisePropertyChanged("ExtensionData");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool registered {
            get {
                return this.registeredField;
            }
            set {
                this.registeredField = value;
                this.RaisePropertyChanged("registered");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string registrationMessage {
            get {
                return this.registrationMessageField;
            }
            set {
                this.registrationMessageField = value;
                this.RaisePropertyChanged("registrationMessage");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string mobileNumber {
            get {
                return this.mobileNumberField;
            }
            set {
                this.mobileNumberField = value;
                this.RaisePropertyChanged("mobileNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string accountNumber {
            get {
                return this.accountNumberField;
            }
            set {
                this.accountNumberField = value;
                this.RaisePropertyChanged("accountNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime registrationTime {
            get {
                return this.registrationTimeField;
            }
            set {
                this.registrationTimeField = value;
                this.RaisePropertyChanged("registrationTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class ExtensionDataObject : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class Account_Enquiry_Detail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hostTransaction_StatusField;
        
        private string schmCodeField;
        
        private string schmTypeField;
        
        private string acctCurrField;
        
        private string branchIdField;
        
        private string branchNameField;
        
        private string addr1Field;
        
        private string addr2Field;
        
        private string addr3Field;
        
        private string lastNameField;
        
        private string firstNameField;
        
        private string middleNameField;
        
        private string nameField;
        
        private string custIdField;
        
        private string acctIdField;
        
        private string titlePrefixField;
        
        private string bankAcctStatusCodeField;
        
        private string acctOpenDtField;
        
        private string error_CodeField;
        
        private string error_DescriptionField;
        
        private string successOrFailureField;
        
        private string aCCTNAMEField;
        
        private string aVAILDRCRINDField;
        
        private string dRAWINGPOWERDRCRINDField;
        
        private string eFFAVAILDRCRINDField;
        
        private string fLOATDRCRINDField;
        
        private string fREEZESTATUSField;
        
        private string lEDGERDRCRINDField;
        
        private string lIENCRDRINDField;
        
        private string sHADOWDRCRINDField;
        
        private string aCCTBALCRDRINDField;
        
        private string fUTBALCRDRINDField;
        
        private string lEDGER_BalField;
        
        private string aVAIL_BalField;
        
        private string eFFAVL_BalField;
        
        private string fLOAT_BalField;
        
        private string lIEN_BalField;
        
        private string dRWPWR_BalField;
        
        private string aCCBAL_BalField;
        
        private string sHADOW_BalField;
        
        private string fUTBAL_BalField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HostTransaction_Status {
            get {
                return this.hostTransaction_StatusField;
            }
            set {
                this.hostTransaction_StatusField = value;
                this.RaisePropertyChanged("HostTransaction_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SchmCode {
            get {
                return this.schmCodeField;
            }
            set {
                this.schmCodeField = value;
                this.RaisePropertyChanged("SchmCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SchmType {
            get {
                return this.schmTypeField;
            }
            set {
                this.schmTypeField = value;
                this.RaisePropertyChanged("SchmType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AcctCurr {
            get {
                return this.acctCurrField;
            }
            set {
                this.acctCurrField = value;
                this.RaisePropertyChanged("AcctCurr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string BranchId {
            get {
                return this.branchIdField;
            }
            set {
                this.branchIdField = value;
                this.RaisePropertyChanged("BranchId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string BranchName {
            get {
                return this.branchNameField;
            }
            set {
                this.branchNameField = value;
                this.RaisePropertyChanged("BranchName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Addr1 {
            get {
                return this.addr1Field;
            }
            set {
                this.addr1Field = value;
                this.RaisePropertyChanged("Addr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Addr2 {
            get {
                return this.addr2Field;
            }
            set {
                this.addr2Field = value;
                this.RaisePropertyChanged("Addr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Addr3 {
            get {
                return this.addr3Field;
            }
            set {
                this.addr3Field = value;
                this.RaisePropertyChanged("Addr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string LastName {
            get {
                return this.lastNameField;
            }
            set {
                this.lastNameField = value;
                this.RaisePropertyChanged("LastName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string FirstName {
            get {
                return this.firstNameField;
            }
            set {
                this.firstNameField = value;
                this.RaisePropertyChanged("FirstName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string MiddleName {
            get {
                return this.middleNameField;
            }
            set {
                this.middleNameField = value;
                this.RaisePropertyChanged("MiddleName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string CustId {
            get {
                return this.custIdField;
            }
            set {
                this.custIdField = value;
                this.RaisePropertyChanged("CustId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string AcctId {
            get {
                return this.acctIdField;
            }
            set {
                this.acctIdField = value;
                this.RaisePropertyChanged("AcctId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string TitlePrefix {
            get {
                return this.titlePrefixField;
            }
            set {
                this.titlePrefixField = value;
                this.RaisePropertyChanged("TitlePrefix");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string BankAcctStatusCode {
            get {
                return this.bankAcctStatusCodeField;
            }
            set {
                this.bankAcctStatusCodeField = value;
                this.RaisePropertyChanged("BankAcctStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string AcctOpenDt {
            get {
                return this.acctOpenDtField;
            }
            set {
                this.acctOpenDtField = value;
                this.RaisePropertyChanged("AcctOpenDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string Error_Code {
            get {
                return this.error_CodeField;
            }
            set {
                this.error_CodeField = value;
                this.RaisePropertyChanged("Error_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public string Error_Description {
            get {
                return this.error_DescriptionField;
            }
            set {
                this.error_DescriptionField = value;
                this.RaisePropertyChanged("Error_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string SuccessOrFailure {
            get {
                return this.successOrFailureField;
            }
            set {
                this.successOrFailureField = value;
                this.RaisePropertyChanged("SuccessOrFailure");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string ACCTNAME {
            get {
                return this.aCCTNAMEField;
            }
            set {
                this.aCCTNAMEField = value;
                this.RaisePropertyChanged("ACCTNAME");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public string AVAILDRCRIND {
            get {
                return this.aVAILDRCRINDField;
            }
            set {
                this.aVAILDRCRINDField = value;
                this.RaisePropertyChanged("AVAILDRCRIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string DRAWINGPOWERDRCRIND {
            get {
                return this.dRAWINGPOWERDRCRINDField;
            }
            set {
                this.dRAWINGPOWERDRCRINDField = value;
                this.RaisePropertyChanged("DRAWINGPOWERDRCRIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public string EFFAVAILDRCRIND {
            get {
                return this.eFFAVAILDRCRINDField;
            }
            set {
                this.eFFAVAILDRCRINDField = value;
                this.RaisePropertyChanged("EFFAVAILDRCRIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public string FLOATDRCRIND {
            get {
                return this.fLOATDRCRINDField;
            }
            set {
                this.fLOATDRCRINDField = value;
                this.RaisePropertyChanged("FLOATDRCRIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=26)]
        public string FREEZESTATUS {
            get {
                return this.fREEZESTATUSField;
            }
            set {
                this.fREEZESTATUSField = value;
                this.RaisePropertyChanged("FREEZESTATUS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=27)]
        public string LEDGERDRCRIND {
            get {
                return this.lEDGERDRCRINDField;
            }
            set {
                this.lEDGERDRCRINDField = value;
                this.RaisePropertyChanged("LEDGERDRCRIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public string LIENCRDRIND {
            get {
                return this.lIENCRDRINDField;
            }
            set {
                this.lIENCRDRINDField = value;
                this.RaisePropertyChanged("LIENCRDRIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public string SHADOWDRCRIND {
            get {
                return this.sHADOWDRCRINDField;
            }
            set {
                this.sHADOWDRCRINDField = value;
                this.RaisePropertyChanged("SHADOWDRCRIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string ACCTBALCRDRIND {
            get {
                return this.aCCTBALCRDRINDField;
            }
            set {
                this.aCCTBALCRDRINDField = value;
                this.RaisePropertyChanged("ACCTBALCRDRIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string FUTBALCRDRIND {
            get {
                return this.fUTBALCRDRINDField;
            }
            set {
                this.fUTBALCRDRINDField = value;
                this.RaisePropertyChanged("FUTBALCRDRIND");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string LEDGER_Bal {
            get {
                return this.lEDGER_BalField;
            }
            set {
                this.lEDGER_BalField = value;
                this.RaisePropertyChanged("LEDGER_Bal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string AVAIL_Bal {
            get {
                return this.aVAIL_BalField;
            }
            set {
                this.aVAIL_BalField = value;
                this.RaisePropertyChanged("AVAIL_Bal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public string EFFAVL_Bal {
            get {
                return this.eFFAVL_BalField;
            }
            set {
                this.eFFAVL_BalField = value;
                this.RaisePropertyChanged("EFFAVL_Bal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string FLOAT_Bal {
            get {
                return this.fLOAT_BalField;
            }
            set {
                this.fLOAT_BalField = value;
                this.RaisePropertyChanged("FLOAT_Bal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string LIEN_Bal {
            get {
                return this.lIEN_BalField;
            }
            set {
                this.lIEN_BalField = value;
                this.RaisePropertyChanged("LIEN_Bal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string DRWPWR_Bal {
            get {
                return this.dRWPWR_BalField;
            }
            set {
                this.dRWPWR_BalField = value;
                this.RaisePropertyChanged("DRWPWR_Bal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string ACCBAL_Bal {
            get {
                return this.aCCBAL_BalField;
            }
            set {
                this.aCCBAL_BalField = value;
                this.RaisePropertyChanged("ACCBAL_Bal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public string SHADOW_Bal {
            get {
                return this.sHADOW_BalField;
            }
            set {
                this.sHADOW_BalField = value;
                this.RaisePropertyChanged("SHADOW_Bal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string FUTBAL_Bal {
            get {
                return this.fUTBAL_BalField;
            }
            set {
                this.fUTBAL_BalField = value;
                this.RaisePropertyChanged("FUTBAL_Bal");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class Statement : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string txn_DateField;
        
        private string txn_AmountField;
        
        private string txn_RefField;
        
        private string txn_DescriptionField;
        
        private string errorCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Txn_Date {
            get {
                return this.txn_DateField;
            }
            set {
                this.txn_DateField = value;
                this.RaisePropertyChanged("Txn_Date");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Txn_Amount {
            get {
                return this.txn_AmountField;
            }
            set {
                this.txn_AmountField = value;
                this.RaisePropertyChanged("Txn_Amount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Txn_Ref {
            get {
                return this.txn_RefField;
            }
            set {
                this.txn_RefField = value;
                this.RaisePropertyChanged("Txn_Ref");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Txn_Description {
            get {
                return this.txn_DescriptionField;
            }
            set {
                this.txn_DescriptionField = value;
                this.RaisePropertyChanged("Txn_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class StatementInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private Statement[] statementsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Statement[] Statements {
            get {
                return this.statementsField;
            }
            set {
                this.statementsField = value;
                this.RaisePropertyChanged("Statements");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class Account : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountNoField;
        
        private string currencyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNo {
            get {
                return this.accountNoField;
            }
            set {
                this.accountNoField = value;
                this.RaisePropertyChanged("AccountNo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Currency {
            get {
                return this.currencyField;
            }
            set {
                this.currencyField = value;
                this.RaisePropertyChanged("Currency");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class AccountInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private Account[] accountsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public Account[] Accounts {
            get {
                return this.accountsField;
            }
            set {
                this.accountsField = value;
                this.RaisePropertyChanged("Accounts");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class Posting_Response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool successField;
        
        private string responseMsgField;
        
        private string referenceIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public bool Success {
            get {
                return this.successField;
            }
            set {
                this.successField = value;
                this.RaisePropertyChanged("Success");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string responseMsg {
            get {
                return this.responseMsgField;
            }
            set {
                this.responseMsgField = value;
                this.RaisePropertyChanged("responseMsg");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string referenceID {
            get {
                return this.referenceIDField;
            }
            set {
                this.referenceIDField = value;
                this.RaisePropertyChanged("referenceID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class Finacle_Response_Detail : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hostTransaction_StatusField;
        
        private string parm_ChannelRefNum_RespField;
        
        private string resp_CodeField;
        
        private string resp_RemarksField;
        
        private string off_UsRefNumField;
        
        private string error_CodeField;
        
        private string error_DescriptionField;
        
        private string successOrFailureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HostTransaction_Status {
            get {
                return this.hostTransaction_StatusField;
            }
            set {
                this.hostTransaction_StatusField = value;
                this.RaisePropertyChanged("HostTransaction_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Parm_ChannelRefNum_Resp {
            get {
                return this.parm_ChannelRefNum_RespField;
            }
            set {
                this.parm_ChannelRefNum_RespField = value;
                this.RaisePropertyChanged("Parm_ChannelRefNum_Resp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Resp_Code {
            get {
                return this.resp_CodeField;
            }
            set {
                this.resp_CodeField = value;
                this.RaisePropertyChanged("Resp_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Resp_Remarks {
            get {
                return this.resp_RemarksField;
            }
            set {
                this.resp_RemarksField = value;
                this.RaisePropertyChanged("Resp_Remarks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Off_UsRefNum {
            get {
                return this.off_UsRefNumField;
            }
            set {
                this.off_UsRefNumField = value;
                this.RaisePropertyChanged("Off_UsRefNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string Error_Code {
            get {
                return this.error_CodeField;
            }
            set {
                this.error_CodeField = value;
                this.RaisePropertyChanged("Error_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string Error_Description {
            get {
                return this.error_DescriptionField;
            }
            set {
                this.error_DescriptionField = value;
                this.RaisePropertyChanged("Error_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string SuccessOrFailure {
            get {
                return this.successOrFailureField;
            }
            set {
                this.successOrFailureField = value;
                this.RaisePropertyChanged("SuccessOrFailure");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class Account_Lien : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string hostTransaction_StatusField;
        
        private string requestUUIDField;
        
        private string acidField;
        
        private string currencyCodeField;
        
        private string availableBalanceField;
        
        private string fFDBalanceField;
        
        private string floatingBalanceField;
        
        private string ledgerBalanceField;
        
        private string userDefinedBalanceField;
        
        private string accountStatusField;
        
        private string stanField;
        
        private string valueDateField;
        
        private string tHBField;
        
        private string error_CodeField;
        
        private string error_DescriptionField;
        
        private string successOrFailureField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string HostTransaction_Status {
            get {
                return this.hostTransaction_StatusField;
            }
            set {
                this.hostTransaction_StatusField = value;
                this.RaisePropertyChanged("HostTransaction_Status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string RequestUUID {
            get {
                return this.requestUUIDField;
            }
            set {
                this.requestUUIDField = value;
                this.RaisePropertyChanged("RequestUUID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string acid {
            get {
                return this.acidField;
            }
            set {
                this.acidField = value;
                this.RaisePropertyChanged("acid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string currencyCode {
            get {
                return this.currencyCodeField;
            }
            set {
                this.currencyCodeField = value;
                this.RaisePropertyChanged("currencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string availableBalance {
            get {
                return this.availableBalanceField;
            }
            set {
                this.availableBalanceField = value;
                this.RaisePropertyChanged("availableBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string fFDBalance {
            get {
                return this.fFDBalanceField;
            }
            set {
                this.fFDBalanceField = value;
                this.RaisePropertyChanged("fFDBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string floatingBalance {
            get {
                return this.floatingBalanceField;
            }
            set {
                this.floatingBalanceField = value;
                this.RaisePropertyChanged("floatingBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ledgerBalance {
            get {
                return this.ledgerBalanceField;
            }
            set {
                this.ledgerBalanceField = value;
                this.RaisePropertyChanged("ledgerBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string userDefinedBalance {
            get {
                return this.userDefinedBalanceField;
            }
            set {
                this.userDefinedBalanceField = value;
                this.RaisePropertyChanged("userDefinedBalance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string accountStatus {
            get {
                return this.accountStatusField;
            }
            set {
                this.accountStatusField = value;
                this.RaisePropertyChanged("accountStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string stan {
            get {
                return this.stanField;
            }
            set {
                this.stanField = value;
                this.RaisePropertyChanged("stan");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string valueDate {
            get {
                return this.valueDateField;
            }
            set {
                this.valueDateField = value;
                this.RaisePropertyChanged("valueDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string THB {
            get {
                return this.tHBField;
            }
            set {
                this.tHBField = value;
                this.RaisePropertyChanged("THB");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public string Error_Code {
            get {
                return this.error_CodeField;
            }
            set {
                this.error_CodeField = value;
                this.RaisePropertyChanged("Error_Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string Error_Description {
            get {
                return this.error_DescriptionField;
            }
            set {
                this.error_DescriptionField = value;
                this.RaisePropertyChanged("Error_Description");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string SuccessOrFailure {
            get {
                return this.successOrFailureField;
            }
            set {
                this.successOrFailureField = value;
                this.RaisePropertyChanged("SuccessOrFailure");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.4084.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://10.237.61.33:62137/Finacle_Bridge_ST.asmx/")]
    public partial class TrnStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string status_ResponseField;
        
        private string status_DescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Status_Response {
            get {
                return this.status_ResponseField;
            }
            set {
                this.status_ResponseField = value;
                this.RaisePropertyChanged("Status_Response");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Status_Description {
            get {
                return this.status_DescriptionField;
            }
            set {
                this.status_DescriptionField = value;
                this.RaisePropertyChanged("Status_Description");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Finacle_BridgeSoapChannel : e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_BridgeSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Finacle_BridgeSoapClient : System.ServiceModel.ClientBase<e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_BridgeSoap>, e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_BridgeSoap {
        
        public Finacle_BridgeSoapClient() {
        }
        
        public Finacle_BridgeSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Finacle_BridgeSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Finacle_BridgeSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Finacle_BridgeSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int CheckStatus() {
            return base.Channel.CheckStatus();
        }
        
        public string generateRandom() {
            return base.Channel.generateRandom();
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.registration_Response autoRegister(string userID, string userPassword, string mobileNumber, string accountNumber, string accountName, string currencyCode, string chargeType, string Product, string Provider, string registationCRUD_Action, string IDNumber, string IDType_IorP, string IDType_LorF) {
            return base.Channel.autoRegister(userID, userPassword, mobileNumber, accountNumber, accountName, currencyCode, chargeType, Product, Provider, registationCRUD_Action, IDNumber, IDType_IorP, IDType_LorF);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.registration_Response autoRegister_Account(string userID, string userPassword, string mobileNumber, string accountNumber) {
            return base.Channel.autoRegister_Account(userID, userPassword, mobileNumber, accountNumber);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.registration_Response autoRegister_Card_Account(string userID, string userPassword, string mobileNumber, string cardNumber, string accountNumber) {
            return base.Channel.autoRegister_Card_Account(userID, userPassword, mobileNumber, cardNumber, accountNumber);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.registration_Response autoRegister_Card(string userID, string userPassword, string mobileNumber, string cardNumber) {
            return base.Channel.autoRegister_Card(userID, userPassword, mobileNumber, cardNumber);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.TrnStatus Query_Payment_Status_ZeePay(string channelID, string sourceReference, string originalTransactionID) {
            return base.Channel.Query_Payment_Status_ZeePay(channelID, sourceReference, originalTransactionID);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Account_Lien MarkUnMarkLien(string SR_UserID, string SR_Password, string channelID, string Param_AccountNo, string Param_Amount, string Param_Currency, string Param_BranchID, string Param_RequestUUID, string ParamMarkP_or_UnMarkN, string sourceSystem) {
            return base.Channel.MarkUnMarkLien(SR_UserID, SR_Password, channelID, Param_AccountNo, Param_Amount, Param_Currency, Param_BranchID, Param_RequestUUID, ParamMarkP_or_UnMarkN, sourceSystem);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_Response_Detail PostToFinacle_ZeePay(
                    string SR_UserID, 
                    string SR_Password, 
                    string Param1_channelId, 
                    string Param1_RequestUUID, 
                    string Parm1_ChannelRefNum, 
                    bool Parm1_ReversalFlag, 
                    string Parm1_OriginalChannelRefNum, 
                    string Parm1_TranAmount, 
                    string Parm1_TranCrncy, 
                    string Parm1_DrAcctNo, 
                    string Parm1_CrAcctNo, 
                    string Parm1_CrValueDate, 
                    string Parm1_DrBICCode, 
                    string Parm1_CrBICCode, 
                    string Parm1_DrAcctName, 
                    string Parm1_DrAcctAddress1, 
                    string Parm1_DrAcctAddress2, 
                    string Parm1_DrAcctAddress3, 
                    string Parm1_DrTranParticulars, 
                    string Parm1_DrTranRemarks1, 
                    string Parm1_DrTranRemarks2, 
                    string Parm1_CrTranParticulars, 
                    string Parm1_CrTranRemarks1, 
                    string Parm1_CrTranRemarks2, 
                    string Parm1_TranParticularsCodeDr, 
                    string Parm1_TranParticularsCodeCr, 
                    string Parm1_SourceChannel, 
                    string Parm1_DrForcePostFlag, 
                    string Parm1_CrAcctAddress1, 
                    string Parm1_CrAcctAddress2, 
                    string Parm1_CrAcctAddress3, 
                    string ExtraDetails) {
            return base.Channel.PostToFinacle_ZeePay(SR_UserID, SR_Password, Param1_channelId, Param1_RequestUUID, Parm1_ChannelRefNum, Parm1_ReversalFlag, Parm1_OriginalChannelRefNum, Parm1_TranAmount, Parm1_TranCrncy, Parm1_DrAcctNo, Parm1_CrAcctNo, Parm1_CrValueDate, Parm1_DrBICCode, Parm1_CrBICCode, Parm1_DrAcctName, Parm1_DrAcctAddress1, Parm1_DrAcctAddress2, Parm1_DrAcctAddress3, Parm1_DrTranParticulars, Parm1_DrTranRemarks1, Parm1_DrTranRemarks2, Parm1_CrTranParticulars, Parm1_CrTranRemarks1, Parm1_CrTranRemarks2, Parm1_TranParticularsCodeDr, Parm1_TranParticularsCodeCr, Parm1_SourceChannel, Parm1_DrForcePostFlag, Parm1_CrAcctAddress1, Parm1_CrAcctAddress2, Parm1_CrAcctAddress3, ExtraDetails);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_Response_Detail PostToEDMI(
                    string SR_UserID, 
                    string SR_Password, 
                    string Param1_channelId, 
                    string Param1_RequestUUID, 
                    string Parm1_ChannelRefNum, 
                    bool Parm1_ReversalFlag, 
                    string Parm1_OriginalChannelRefNum, 
                    string Parm1_TranAmount, 
                    string Parm1_TranCrncy, 
                    string Parm1_DrAcctNo, 
                    string Parm1_CrAcctNo, 
                    string Parm1_CrValueDate, 
                    string Parm1_DrBICCode, 
                    string Parm1_CrBICCode, 
                    string Parm1_DrAcctName, 
                    string Parm1_DrAcctAddress1, 
                    string Parm1_DrTranParticulars, 
                    string Parm1_DrTranRemarks1, 
                    string Parm1_DrTranRemarks2, 
                    string Parm1_CrTranParticulars, 
                    string Parm1_CrTranRemarks1, 
                    string Parm1_CrTranRemarks2, 
                    string Parm1_TranParticularsCodeDr, 
                    string Parm1_TranParticularsCodeCr, 
                    string Parm1_SourceChannel) {
            return base.Channel.PostToEDMI(SR_UserID, SR_Password, Param1_channelId, Param1_RequestUUID, Parm1_ChannelRefNum, Parm1_ReversalFlag, Parm1_OriginalChannelRefNum, Parm1_TranAmount, Parm1_TranCrncy, Parm1_DrAcctNo, Parm1_CrAcctNo, Parm1_CrValueDate, Parm1_DrBICCode, Parm1_CrBICCode, Parm1_DrAcctName, Parm1_DrAcctAddress1, Parm1_DrTranParticulars, Parm1_DrTranRemarks1, Parm1_DrTranRemarks2, Parm1_CrTranParticulars, Parm1_CrTranRemarks1, Parm1_CrTranRemarks2, Parm1_TranParticularsCodeDr, Parm1_TranParticularsCodeCr, Parm1_SourceChannel);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Posting_Response ReverseTransaction_SCB(string XML_Ref_C, string ChannelRefNum_C, string Source_Channel, string Trn_ID, string AccountNo, double trnAmount, string TrnRemarks, bool usePseudoResponse, string TRANSACTION_TYPE) {
            return base.Channel.ReverseTransaction_SCB(XML_Ref_C, ChannelRefNum_C, Source_Channel, Trn_ID, AccountNo, trnAmount, TrnRemarks, usePseudoResponse, TRANSACTION_TYPE);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_Response_Detail PostToFinacle(
                    string SR_UserID, 
                    string SR_Password, 
                    string Param1_channelId, 
                    string Param1_RequestUUID, 
                    string Parm1_ChannelRefNum, 
                    bool Parm1_ReversalFlag, 
                    string Parm1_OriginalChannelRefNum, 
                    string Parm1_TranAmount, 
                    string Parm1_TranCrncy, 
                    string Parm1_DrAcctNo, 
                    string Parm1_CrAcctNo, 
                    string Parm1_CrValueDate, 
                    string Parm1_DrBICCode, 
                    string Parm1_CrBICCode, 
                    string Parm1_DrAcctName, 
                    string Parm1_DrAcctAddress1, 
                    string Parm1_DrTranParticulars, 
                    string Parm1_DrTranRemarks1, 
                    string Parm1_DrTranRemarks2, 
                    string Parm1_CrTranParticulars, 
                    string Parm1_CrTranRemarks1, 
                    string Parm1_CrTranRemarks2, 
                    string Parm1_TranParticularsCodeDr, 
                    string Parm1_TranParticularsCodeCr, 
                    string Parm1_SourceChannel) {
            return base.Channel.PostToFinacle(SR_UserID, SR_Password, Param1_channelId, Param1_RequestUUID, Parm1_ChannelRefNum, Parm1_ReversalFlag, Parm1_OriginalChannelRefNum, Parm1_TranAmount, Parm1_TranCrncy, Parm1_DrAcctNo, Parm1_CrAcctNo, Parm1_CrValueDate, Parm1_DrBICCode, Parm1_CrBICCode, Parm1_DrAcctName, Parm1_DrAcctAddress1, Parm1_DrTranParticulars, Parm1_DrTranRemarks1, Parm1_DrTranRemarks2, Parm1_CrTranParticulars, Parm1_CrTranRemarks1, Parm1_CrTranRemarks2, Parm1_TranParticularsCodeDr, Parm1_TranParticularsCodeCr, Parm1_SourceChannel);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_Response_Detail PostToFinacle_WithForcePostFlag(
                    string SR_UserID, 
                    string SR_Password, 
                    string Param1_channelId, 
                    string Param1_RequestUUID, 
                    string Parm1_ChannelRefNum, 
                    bool Parm1_ReversalFlag, 
                    string Parm1_OriginalChannelRefNum, 
                    string Parm1_TranAmount, 
                    string Parm1_TranCrncy, 
                    string Parm1_DrAcctNo, 
                    string Parm1_CrAcctNo, 
                    string Parm1_CrValueDate, 
                    string Parm1_DrBICCode, 
                    string Parm1_CrBICCode, 
                    string Parm1_DrAcctName, 
                    string Parm1_DrAcctAddress1, 
                    string Parm1_DrTranParticulars, 
                    string Parm1_DrTranRemarks1, 
                    string Parm1_DrTranRemarks2, 
                    string Parm1_CrTranParticulars, 
                    string Parm1_CrTranRemarks1, 
                    string Parm1_CrTranRemarks2, 
                    string Parm1_TranParticularsCodeDr, 
                    string Parm1_TranParticularsCodeCr, 
                    string Parm1_SourceChannel, 
                    string Parm1_DrForcePostFlag) {
            return base.Channel.PostToFinacle_WithForcePostFlag(SR_UserID, SR_Password, Param1_channelId, Param1_RequestUUID, Parm1_ChannelRefNum, Parm1_ReversalFlag, Parm1_OriginalChannelRefNum, Parm1_TranAmount, Parm1_TranCrncy, Parm1_DrAcctNo, Parm1_CrAcctNo, Parm1_CrValueDate, Parm1_DrBICCode, Parm1_CrBICCode, Parm1_DrAcctName, Parm1_DrAcctAddress1, Parm1_DrTranParticulars, Parm1_DrTranRemarks1, Parm1_DrTranRemarks2, Parm1_CrTranParticulars, Parm1_CrTranRemarks1, Parm1_CrTranRemarks2, Parm1_TranParticularsCodeDr, Parm1_TranParticularsCodeCr, Parm1_SourceChannel, Parm1_DrForcePostFlag);
        }
        
        public string GetToken(string userId, string password, string product, string NetworkProviderID, string telephoneNo) {
            return base.Channel.GetToken(userId, password, product, NetworkProviderID, telephoneNo);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.AccountInfo GetAccounts(long tokenId, string telephoneNo) {
            return base.Channel.GetAccounts(tokenId, telephoneNo);
        }
        
        public string GetAccountBalance(long tokenId, string telephoneNo, string accountNo) {
            return base.Channel.GetAccountBalance(tokenId, telephoneNo, accountNo);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.StatementInfo GetAccountStatement(long tokenId, string telephoneNo, string accountNo) {
            return base.Channel.GetAccountStatement(tokenId, telephoneNo, accountNo);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.StatementInfo GetAccountStatement_ZeePay(string SR_UserID, string SR_Password, string accountNo, string UniqueReference) {
            return base.Channel.GetAccountStatement_ZeePay(SR_UserID, SR_Password, accountNo, UniqueReference);
        }
        
        public string ResetPassword(string telephoneNo, string NetworkProviderID, string product, string oldPassword, string newPassword, string newPasswordConfirm) {
            return base.Channel.ResetPassword(telephoneNo, NetworkProviderID, product, oldPassword, newPassword, newPasswordConfirm);
        }
        
        public string InternalTransfer(long tokenId, string telephoneNo, string sourceAccountNo, string destinationAccountNo, string sourceReference, double transferAmount) {
            return base.Channel.InternalTransfer(tokenId, telephoneNo, sourceAccountNo, destinationAccountNo, sourceReference, transferAmount);
        }
        
        public string ThirdPartyPayment(long tokenId, string telephoneNo, string sourceAccountNo, string destinationAccountNo, string destinationSWIFTCode, string sourceReference, string beneficiaryName, double paymentAmount, string Extra_Narrative1, string Extra_Narrative2) {
            return base.Channel.ThirdPartyPayment(tokenId, telephoneNo, sourceAccountNo, destinationAccountNo, destinationSWIFTCode, sourceReference, beneficiaryName, paymentAmount, Extra_Narrative1, Extra_Narrative2);
        }
        
        public string BillPayment(string userId, string password, long tokenId, string telephoneNo, string sourceAccountNo, string ServiceProviderID, string CustomerID, string sourceReference, string sourceNarrative, double paymentAmount, string Extra_Narrative1, string Extra_Narrative2) {
            return base.Channel.BillPayment(userId, password, tokenId, telephoneNo, sourceAccountNo, ServiceProviderID, CustomerID, sourceReference, sourceNarrative, paymentAmount, Extra_Narrative1, Extra_Narrative2);
        }
        
        public string Get_BeneficiaryName(string Beneficiary_Account) {
            return base.Channel.Get_BeneficiaryName(Beneficiary_Account);
        }
        
        public string Verify_BeneficiaryName(string ServiceProviderID, string CustomerID) {
            return base.Channel.Verify_BeneficiaryName(ServiceProviderID, CustomerID);
        }
        
        public string Get_Account_From_MobileNumber(string MobileNumber) {
            return base.Channel.Get_Account_From_MobileNumber(MobileNumber);
        }
        
        public string ZIPIT_SEND(string tokenId, string sourceAccount, string telephoneNo, string destinationInstitute, string destinationAccount, string sourceReference, long paymentAmount) {
            return base.Channel.ZIPIT_SEND(tokenId, sourceAccount, telephoneNo, destinationInstitute, destinationAccount, sourceReference, paymentAmount);
        }
        
        public string ZIPIT_SMART_REQUEST(string Api_Key, string User_Name, string Password, System.DateTime transmissionDate, string merchantCode, string channel, string acquiringInstID, string extendedTrantype) {
            return base.Channel.ZIPIT_SMART_REQUEST(Api_Key, User_Name, Password, transmissionDate, merchantCode, channel, acquiringInstID, extendedTrantype);
        }
        
        public string ZIPIT_SEND_KYC(string tokenId, string sourceAccount, string telephoneNo, string destinationInstitute, string destinationAccount, string sourceReference, long paymentAmount, string IDNumber_KYC, string sourceAccount_KYC, string AccountName_KYC, string extraDetail_1, string extraDetail_2, string extraDetail_3) {
            return base.Channel.ZIPIT_SEND_KYC(tokenId, sourceAccount, telephoneNo, destinationInstitute, destinationAccount, sourceReference, paymentAmount, IDNumber_KYC, sourceAccount_KYC, AccountName_KYC, extraDetail_1, extraDetail_2, extraDetail_3);
        }
        
        public System.Data.DataTable qry_FinTransaction(string AccountNo, string ChannelRefNum_C, string MobileNo) {
            return base.Channel.qry_FinTransaction(AccountNo, ChannelRefNum_C, MobileNo);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Posting_Response ReverseTransaction_Post_First(string XML_Ref_C, string ChannelRefNum_C, string Source_Channel, string Trn_ID, string AccountNo, string TrnRemarks) {
            return base.Channel.ReverseTransaction_Post_First(XML_Ref_C, ChannelRefNum_C, Source_Channel, Trn_ID, AccountNo, TrnRemarks);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Posting_Response ReverseTransaction_ZeePay(string SR_UserID, string SR_Password, string XML_Ref_C, string ChannelRefNum, string Source_Channel, string Trn_ID, string AccountNo, string TrnRemarks) {
            return base.Channel.ReverseTransaction_ZeePay(SR_UserID, SR_Password, XML_Ref_C, ChannelRefNum, Source_Channel, Trn_ID, AccountNo, TrnRemarks);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Posting_Response ReverseTransaction(string XML_Ref_C, string ChannelRefNum_C, string Source_Channel, string Trn_ID, string AccountNo, string TrnRemarks) {
            return base.Channel.ReverseTransaction(XML_Ref_C, ChannelRefNum_C, Source_Channel, Trn_ID, AccountNo, TrnRemarks);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Account_Enquiry_Detail Finacle_AccountEnquiry(string Param_Account, string Param_RequestUUID, bool UsePseudoResponse, string Parm_SourceChannel) {
            return base.Channel.Finacle_AccountEnquiry(Param_Account, Param_RequestUUID, UsePseudoResponse, Parm_SourceChannel);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.Finacle_Bridge.Finacle_Response_Detail ReverseZeePayTransaction_local(string SR_UserID, string SR_Password, string channelId, string RequestUUID, string ChannelRefNum, string RequestXML) {
            return base.Channel.ReverseZeePayTransaction_local(SR_UserID, SR_Password, channelId, RequestUUID, ChannelRefNum, RequestXML);
        }
    }
}
