//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_Verify_BACK_OFFICE_Service_Interface.selcommobile {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="syncRequestType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class syncRequestType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.credentialsType credentialsField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncRequest payloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.credentialsType credentials {
            get {
                return this.credentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.credentialsField, value) != true)) {
                    this.credentialsField = value;
                    this.RaisePropertyChanged("credentials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncRequest payload {
            get {
                return this.payloadField;
            }
            set {
                if ((object.ReferenceEquals(this.payloadField, value) != true)) {
                    this.payloadField = value;
                    this.RaisePropertyChanged("payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="credentialsType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class credentialsType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string usernameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string passwordField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="syncRequest", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class syncRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msisdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.msisdnField, value) != true)) {
                    this.msisdnField = value;
                    this.RaisePropertyChanged("msisdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="statusType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class statusType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string code {
            get {
                return this.codeField;
            }
            set {
                if ((object.ReferenceEquals(this.codeField, value) != true)) {
                    this.codeField = value;
                    this.RaisePropertyChanged("code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="syncAccountRequestType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class syncAccountRequestType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.credentialsType credentialsField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequest payloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.credentialsType credentials {
            get {
                return this.credentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.credentialsField, value) != true)) {
                    this.credentialsField = value;
                    this.RaisePropertyChanged("credentials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequest payload {
            get {
                return this.payloadField;
            }
            set {
                if ((object.ReferenceEquals(this.payloadField, value) != true)) {
                    this.payloadField = value;
                    this.RaisePropertyChanged("payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="syncAccountRequest", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class syncAccountRequest : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msisdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string typeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.msisdnField, value) != true)) {
                    this.msisdnField = value;
                    this.RaisePropertyChanged("msisdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string type {
            get {
                return this.typeField;
            }
            set {
                if ((object.ReferenceEquals(this.typeField, value) != true)) {
                    this.typeField = value;
                    this.RaisePropertyChanged("type");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                if ((object.ReferenceEquals(this.accountField, value) != true)) {
                    this.accountField = value;
                    this.RaisePropertyChanged("account");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fetchW2BRequestType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class fetchW2BRequestType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.credentialsType credentialsField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.w2bRequestType payloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.credentialsType credentials {
            get {
                return this.credentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.credentialsField, value) != true)) {
                    this.credentialsField = value;
                    this.RaisePropertyChanged("credentials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.w2bRequestType payload {
            get {
                return this.payloadField;
            }
            set {
                if ((object.ReferenceEquals(this.payloadField, value) != true)) {
                    this.payloadField = value;
                    this.RaisePropertyChanged("payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="w2bRequestType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class w2bRequestType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string servicetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchantidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string servicetype {
            get {
                return this.servicetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.servicetypeField, value) != true)) {
                    this.servicetypeField = value;
                    this.RaisePropertyChanged("servicetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string merchantid {
            get {
                return this.merchantidField;
            }
            set {
                if ((object.ReferenceEquals(this.merchantidField, value) != true)) {
                    this.merchantidField = value;
                    this.RaisePropertyChanged("merchantid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fetchW2BResponseType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class fetchW2BResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BStatusType statusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NoOfTransactionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.ArrayOfTran payloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BStatusType status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string NoOfTransactions {
            get {
                return this.NoOfTransactionsField;
            }
            set {
                if ((object.ReferenceEquals(this.NoOfTransactionsField, value) != true)) {
                    this.NoOfTransactionsField = value;
                    this.RaisePropertyChanged("NoOfTransactions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.ArrayOfTran payload {
            get {
                return this.payloadField;
            }
            set {
                if ((object.ReferenceEquals(this.payloadField, value) != true)) {
                    this.payloadField = value;
                    this.RaisePropertyChanged("payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="fetchW2BStatusType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class fetchW2BStatusType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statuscodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string statuscode {
            get {
                return this.statuscodeField;
            }
            set {
                if ((object.ReferenceEquals(this.statuscodeField, value) != true)) {
                    this.statuscodeField = value;
                    this.RaisePropertyChanged("statuscode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfTran", Namespace="http://paypoint.selcommobile.com/webservices/", ItemName="tran")]
    [System.SerializableAttribute()]
    public class ArrayOfTran : System.Collections.Generic.List<e_Verify_BACK_OFFICE_Service_Interface.selcommobile.tran> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="tran", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class tran : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string servicetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string providerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msisdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string consumercodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string merchantidField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string bankref {
            get {
                return this.bankrefField;
            }
            set {
                if ((object.ReferenceEquals(this.bankrefField, value) != true)) {
                    this.bankrefField = value;
                    this.RaisePropertyChanged("bankref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string transid {
            get {
                return this.transidField;
            }
            set {
                if ((object.ReferenceEquals(this.transidField, value) != true)) {
                    this.transidField = value;
                    this.RaisePropertyChanged("transid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                if ((object.ReferenceEquals(this.referenceField, value) != true)) {
                    this.referenceField = value;
                    this.RaisePropertyChanged("reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string servicetype {
            get {
                return this.servicetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.servicetypeField, value) != true)) {
                    this.servicetypeField = value;
                    this.RaisePropertyChanged("servicetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string provider {
            get {
                return this.providerField;
            }
            set {
                if ((object.ReferenceEquals(this.providerField, value) != true)) {
                    this.providerField = value;
                    this.RaisePropertyChanged("provider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                if ((object.ReferenceEquals(this.accountField, value) != true)) {
                    this.accountField = value;
                    this.RaisePropertyChanged("account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.msisdnField, value) != true)) {
                    this.msisdnField = value;
                    this.RaisePropertyChanged("msisdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string consumercode {
            get {
                return this.consumercodeField;
            }
            set {
                if ((object.ReferenceEquals(this.consumercodeField, value) != true)) {
                    this.consumercodeField = value;
                    this.RaisePropertyChanged("consumercode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string merchantid {
            get {
                return this.merchantidField;
            }
            set {
                if ((object.ReferenceEquals(this.merchantidField, value) != true)) {
                    this.merchantidField = value;
                    this.RaisePropertyChanged("merchantid");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="postW2BRequestType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class postW2BRequestType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.credentialsType credentialsField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.tran payloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.credentialsType credentials {
            get {
                return this.credentialsField;
            }
            set {
                if ((object.ReferenceEquals(this.credentialsField, value) != true)) {
                    this.credentialsField = value;
                    this.RaisePropertyChanged("credentials");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.tran payload {
            get {
                return this.payloadField;
            }
            set {
                if ((object.ReferenceEquals(this.payloadField, value) != true)) {
                    this.payloadField = value;
                    this.RaisePropertyChanged("payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="postW2BResponseType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class postW2BResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BStatusType statusField;
        
        private e_Verify_BACK_OFFICE_Service_Interface.selcommobile.w2bPostResponseType payloadField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BStatusType status {
            get {
                return this.statusField;
            }
            set {
                if ((object.ReferenceEquals(this.statusField, value) != true)) {
                    this.statusField = value;
                    this.RaisePropertyChanged("status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=1)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.w2bPostResponseType payload {
            get {
                return this.payloadField;
            }
            set {
                if ((object.ReferenceEquals(this.payloadField, value) != true)) {
                    this.payloadField = value;
                    this.RaisePropertyChanged("payload");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="w2bPostResponseType", Namespace="http://paypoint.selcommobile.com/webservices/")]
    [System.SerializableAttribute()]
    public partial class w2bPostResponseType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string statuscodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string descriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string bankrefField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string servicetypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string transidField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string referenceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string providerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string accountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string msisdnField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string amountField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string consumercodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string resultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string messageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string statuscode {
            get {
                return this.statuscodeField;
            }
            set {
                if ((object.ReferenceEquals(this.statuscodeField, value) != true)) {
                    this.statuscodeField = value;
                    this.RaisePropertyChanged("statuscode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string description {
            get {
                return this.descriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.descriptionField, value) != true)) {
                    this.descriptionField = value;
                    this.RaisePropertyChanged("description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string bankref {
            get {
                return this.bankrefField;
            }
            set {
                if ((object.ReferenceEquals(this.bankrefField, value) != true)) {
                    this.bankrefField = value;
                    this.RaisePropertyChanged("bankref");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string servicetype {
            get {
                return this.servicetypeField;
            }
            set {
                if ((object.ReferenceEquals(this.servicetypeField, value) != true)) {
                    this.servicetypeField = value;
                    this.RaisePropertyChanged("servicetype");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string transid {
            get {
                return this.transidField;
            }
            set {
                if ((object.ReferenceEquals(this.transidField, value) != true)) {
                    this.transidField = value;
                    this.RaisePropertyChanged("transid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string reference {
            get {
                return this.referenceField;
            }
            set {
                if ((object.ReferenceEquals(this.referenceField, value) != true)) {
                    this.referenceField = value;
                    this.RaisePropertyChanged("reference");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string provider {
            get {
                return this.providerField;
            }
            set {
                if ((object.ReferenceEquals(this.providerField, value) != true)) {
                    this.providerField = value;
                    this.RaisePropertyChanged("provider");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=7)]
        public string account {
            get {
                return this.accountField;
            }
            set {
                if ((object.ReferenceEquals(this.accountField, value) != true)) {
                    this.accountField = value;
                    this.RaisePropertyChanged("account");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string msisdn {
            get {
                return this.msisdnField;
            }
            set {
                if ((object.ReferenceEquals(this.msisdnField, value) != true)) {
                    this.msisdnField = value;
                    this.RaisePropertyChanged("msisdn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string amount {
            get {
                return this.amountField;
            }
            set {
                if ((object.ReferenceEquals(this.amountField, value) != true)) {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=10)]
        public string consumercode {
            get {
                return this.consumercodeField;
            }
            set {
                if ((object.ReferenceEquals(this.consumercodeField, value) != true)) {
                    this.consumercodeField = value;
                    this.RaisePropertyChanged("consumercode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string result {
            get {
                return this.resultField;
            }
            set {
                if ((object.ReferenceEquals(this.resultField, value) != true)) {
                    this.resultField = value;
                    this.RaisePropertyChanged("result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                if ((object.ReferenceEquals(this.messageField, value) != true)) {
                    this.messageField = value;
                    this.RaisePropertyChanged("message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/", ConfigurationName="selcommobile.WebServiceSoap")]
    public interface WebServiceSoap {
        
        // CODEGEN: Generating message contract since element name requestData from namespace http://paypoint.selcommobile.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paypoint.selcommobile.com/webservices/syncCustomer", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerResponse syncCustomer(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace http://paypoint.selcommobile.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paypoint.selcommobile.com/webservices/syncCustomerTest", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestResponse syncCustomerTest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace http://paypoint.selcommobile.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paypoint.selcommobile.com/webservices/syncAccount", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountResponse syncAccount(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequest1 request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace http://paypoint.selcommobile.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paypoint.selcommobile.com/webservices/syncAccountTest", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestResponse syncAccountTest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace http://paypoint.selcommobile.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paypoint.selcommobile.com/webservices/fetchW2B", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BResponse fetchW2B(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BRequest request);
        
        // CODEGEN: Generating message contract since element name requestData from namespace http://paypoint.selcommobile.com/webservices/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://paypoint.selcommobile.com/webservices/postW2BResult", ReplyAction="*")]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultResponse postW2BResult(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class syncCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="syncCustomer", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerRequestBody Body;
        
        public syncCustomerRequest() {
        }
        
        public syncCustomerRequest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class syncCustomerRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncRequestType requestData;
        
        public syncCustomerRequestBody() {
        }
        
        public syncCustomerRequestBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncRequestType requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class syncCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="syncCustomerResponse", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerResponseBody Body;
        
        public syncCustomerResponse() {
        }
        
        public syncCustomerResponse(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class syncCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncCustomerResult;
        
        public syncCustomerResponseBody() {
        }
        
        public syncCustomerResponseBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncCustomerResult) {
            this.syncCustomerResult = syncCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class syncCustomerTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="syncCustomerTest", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestRequestBody Body;
        
        public syncCustomerTestRequest() {
        }
        
        public syncCustomerTestRequest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class syncCustomerTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncRequestType requestData;
        
        public syncCustomerTestRequestBody() {
        }
        
        public syncCustomerTestRequestBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncRequestType requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class syncCustomerTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="syncCustomerTestResponse", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestResponseBody Body;
        
        public syncCustomerTestResponse() {
        }
        
        public syncCustomerTestResponse(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class syncCustomerTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncCustomerTestResult;
        
        public syncCustomerTestResponseBody() {
        }
        
        public syncCustomerTestResponseBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncCustomerTestResult) {
            this.syncCustomerTestResult = syncCustomerTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class syncAccountRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="syncAccount", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequest1Body Body;
        
        public syncAccountRequest1() {
        }
        
        public syncAccountRequest1(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequest1Body Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class syncAccountRequest1Body {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequestType requestData;
        
        public syncAccountRequest1Body() {
        }
        
        public syncAccountRequest1Body(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequestType requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class syncAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="syncAccountResponse", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountResponseBody Body;
        
        public syncAccountResponse() {
        }
        
        public syncAccountResponse(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class syncAccountResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncAccountResult;
        
        public syncAccountResponseBody() {
        }
        
        public syncAccountResponseBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncAccountResult) {
            this.syncAccountResult = syncAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class syncAccountTestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="syncAccountTest", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestRequestBody Body;
        
        public syncAccountTestRequest() {
        }
        
        public syncAccountTestRequest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class syncAccountTestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequestType requestData;
        
        public syncAccountTestRequestBody() {
        }
        
        public syncAccountTestRequestBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequestType requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class syncAccountTestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="syncAccountTestResponse", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestResponseBody Body;
        
        public syncAccountTestResponse() {
        }
        
        public syncAccountTestResponse(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class syncAccountTestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncAccountTestResult;
        
        public syncAccountTestResponseBody() {
        }
        
        public syncAccountTestResponseBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncAccountTestResult) {
            this.syncAccountTestResult = syncAccountTestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchW2BRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchW2B", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BRequestBody Body;
        
        public fetchW2BRequest() {
        }
        
        public fetchW2BRequest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class fetchW2BRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BRequestType requestData;
        
        public fetchW2BRequestBody() {
        }
        
        public fetchW2BRequestBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BRequestType requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class fetchW2BResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="fetchW2BResponse", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BResponseBody Body;
        
        public fetchW2BResponse() {
        }
        
        public fetchW2BResponse(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class fetchW2BResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BResponseType fetchW2BResult;
        
        public fetchW2BResponseBody() {
        }
        
        public fetchW2BResponseBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BResponseType fetchW2BResult) {
            this.fetchW2BResult = fetchW2BResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postW2BResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="postW2BResult", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultRequestBody Body;
        
        public postW2BResultRequest() {
        }
        
        public postW2BResultRequest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class postW2BResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BRequestType requestData;
        
        public postW2BResultRequestBody() {
        }
        
        public postW2BResultRequestBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BRequestType requestData) {
            this.requestData = requestData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class postW2BResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="postW2BResultResponse", Namespace="http://paypoint.selcommobile.com/webservices/", Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultResponseBody Body;
        
        public postW2BResultResponse() {
        }
        
        public postW2BResultResponse(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://paypoint.selcommobile.com/webservices/")]
    public partial class postW2BResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResponseType postW2BResultResult;
        
        public postW2BResultResponseBody() {
        }
        
        public postW2BResultResponseBody(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResponseType postW2BResultResult) {
            this.postW2BResultResult = postW2BResultResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceSoapChannel : e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceSoapClient : System.ServiceModel.ClientBase<e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap>, e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap {
        
        public WebServiceSoapClient() {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerResponse e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap.syncCustomer(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerRequest request) {
            return base.Channel.syncCustomer(request);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncCustomer(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncRequestType requestData) {
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerRequest();
            inValue.Body = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerRequestBody();
            inValue.Body.requestData = requestData;
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap)(this)).syncCustomer(inValue);
            return retVal.Body.syncCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestResponse e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap.syncCustomerTest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestRequest request) {
            return base.Channel.syncCustomerTest(request);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncCustomerTest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncRequestType requestData) {
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestRequest();
            inValue.Body = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestRequestBody();
            inValue.Body.requestData = requestData;
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncCustomerTestResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap)(this)).syncCustomerTest(inValue);
            return retVal.Body.syncCustomerTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountResponse e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap.syncAccount(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequest1 request) {
            return base.Channel.syncAccount(request);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncAccount(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequestType requestData) {
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequest1 inValue = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequest1();
            inValue.Body = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequest1Body();
            inValue.Body.requestData = requestData;
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap)(this)).syncAccount(inValue);
            return retVal.Body.syncAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestResponse e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap.syncAccountTest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestRequest request) {
            return base.Channel.syncAccountTest(request);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.statusType syncAccountTest(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountRequestType requestData) {
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestRequest();
            inValue.Body = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestRequestBody();
            inValue.Body.requestData = requestData;
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.syncAccountTestResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap)(this)).syncAccountTest(inValue);
            return retVal.Body.syncAccountTestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BResponse e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap.fetchW2B(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BRequest request) {
            return base.Channel.fetchW2B(request);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BResponseType fetchW2B(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BRequestType requestData) {
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BRequest();
            inValue.Body = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BRequestBody();
            inValue.Body.requestData = requestData;
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.fetchW2BResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap)(this)).fetchW2B(inValue);
            return retVal.Body.fetchW2BResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultResponse e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap.postW2BResult(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultRequest request) {
            return base.Channel.postW2BResult(request);
        }
        
        public e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResponseType postW2BResult(e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BRequestType requestData) {
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultRequest inValue = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultRequest();
            inValue.Body = new e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultRequestBody();
            inValue.Body.requestData = requestData;
            e_Verify_BACK_OFFICE_Service_Interface.selcommobile.postW2BResultResponse retVal = ((e_Verify_BACK_OFFICE_Service_Interface.selcommobile.WebServiceSoap)(this)).postW2BResult(inValue);
            return retVal.Body.postW2BResultResult;
        }
    }
}
